//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class activity
    {
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ขั้นตอนที่")]
        public Nullable<int> stepNum { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ชื่อขั้นตอน")]
        public string stepName { get; set; }
        [DisplayName("อายุ(วัน)")]
        public int age { get; set; }
        [DisplayName("ระยะเวลา(วัน)")]
        public int time { get; set; }
        [DisplayName("กิจกกรรม")]
        public string activity1 { get; set; }
        [DisplayName("ข้อสังเกต")]
        public string notice { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ชื่อขั้นตอนการทำงาน")]
        public int plan { get; set; }

        public virtual theory theory { get; set; }
    }
}
