//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class equipment
    {
        [DisplayName("ประเภทอุปกรณ์")]
        public int equipmentType { get; set; }
        [DisplayName("รหัสอุปกรณ์")]
        public string equipmentID { get; set; }
        [DisplayName("ชื่ออุปกรณ์")]
        public string equipmentName { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("ราคาซื้อ")]
        public Nullable<int> price { get; set; }
        [DisplayName("หน่วยที่ซื้อ")]
        public int unitBuy { get; set; }
        [DisplayName("หน่วยที่ใช้")]
        public int unitUse { get; set; }
        [DisplayName("วันที่ซื้อ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dateBuy { get; set; }
        [DisplayName("เวลางาน(ชม./ไร่)")]
        public Nullable<int> workTime { get; set; }
        [DisplayName("ค่าพลังงานและเชื้อเพลิง/ชม.")]
        public Nullable<int> fuel { get; set; }
        [DisplayName("ประเภทพลังงาน")]
        public Nullable<int> energy { get; set; }
        [DisplayName("รูปภาพอุปกรณ์")]
        public string equipmentImg { get; set; }
        [DisplayName("ลำดับที่")]
        public int IDequip { get; set; }

        public virtual energy energy1 { get; set; }
        public virtual equipmenttype equipmenttype1 { get; set; }
        public virtual unit unit { get; set; }
        public virtual unit unit1 { get; set; }
        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase file_equipmentImg { get; set; }
    }
}