//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filedetail
    {
        public int fileID { get; set; }
        public string fileName { get; set; }
        public string fileContentType { get; set; }
        public Nullable<bool> fileData { get; set; }
    }
}
