// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class fuel
    {
        [DisplayName("ประเภทเชื่้อเพลิงและพลังงาน")]
        public int fuelType { get; set; }
        [DisplayName("ชื่อเชื่้อเพลิงและพลังงาน")]
        public string fuelName { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("ราคาซื้อ")]
        public Nullable<int> price { get; set; }
        [DisplayName("หน่วยที่ซื้อ")]
        public int unitBuy { get; set; }
        [DisplayName("วันที่ซื้อ")]
        public int unitUse { get; set; }
        [DisplayName("รูปภาพเชื่้อเพลิงและพลังงาน")]
        public string fuleImg { get; set; }
        [DisplayName("ลำดับที่")]
        public int IDfule { get; set; }

        public virtual fueltype fueltype1 { get; set; }
        public virtual unit unit { get; set; }
        public virtual unit unit1 { get; set; }
    }
}