//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class labor
    {
        [DisplayName("ประเภทพนักงาน")]
        public int laborType { get; set; }
        [DisplayName("ตำแหน่งงาน")]
        public int position { get; set; }
        [DisplayName("รหัสพนักงาน")]
        public string laborID { get; set; }
        [DisplayName("ชื่อพนักงาน")]
        public string laborName { get; set; }
        [DisplayName("เงินเดือน / ค่าแรง")]
        public Nullable<int> salary { get; set; }
        [DisplayName("วันที่เริ่มทำงาน")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> workDate { get; set; }
        [DisplayName("รูปภาพพนักงาน")]
        public string laborImg { get; set; }
        [DisplayName("ลำดับที่")]
        public int IDlab { get; set; }

        public virtual labortype labortype1 { get; set; }
        public virtual position position1 { get; set; }
        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase file_laborImg { get; set; }
    }
}