//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class projectand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projectand()
        {
            this.standardlists = new HashSet<standardlist>();
        }
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }

        [DisplayName("วันที่ปรับปรุง/แก้ไข")]
        public System.DateTime dataNow { get; set; }
        [DisplayName("ชื่อโครงการ")]
        public string proName { get; set; }
        [DisplayName("วิธีการรับซื้อ")]
        public int buyMethod { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("มาตรฐานการผลิต")]
        public Nullable<int> manuStandards { get; set; }

        public virtual buymethod buymethod1 { get; set; }
        public virtual standard standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<standardlist> standardlists { get; set; }
    }
}
