//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public register()
        {
            this.landplots = new HashSet<landplot>();
        }
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("ชื่อ นามสกุล")]
        public string name { get; set; }
        [DisplayName("ทะเบียนเกษตรกร")]
        public string registerID { get; set; }
        [DisplayName("เลขบัตรประชาชน")]
        [StringLength(13, MinimumLength = 13, ErrorMessage = "กรุณาตรวจหมายเลขบัตรประชาชนอีกครั้ง")]
        public string cardID { get; set; }
        [DisplayName("เพศ")]
        public Nullable<int> gender { get; set; }
        [DisplayName("วัน/เดือน/ปี เกิด")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> birthday { get; set; }
        [DisplayName("เบอร์โทรศัพท์")]
        public int tel { get; set; }
        [DisplayName("อีเมล์")]
        public string email { get; set; }
        [DisplayName("สถานะครอบครัว")]
        public Nullable<int> family { get; set; }
        [DisplayName("บ้านเลขที่")]
        public Nullable<int> no { get; set; }
        [DisplayName("หมู่ที่")]
        public Nullable<int> moo { get; set; }
        [DisplayName("ถนน/ซอย")]
        public string road { get; set; }
        [DisplayName("จังหวัด")]
        public Nullable<int> province { get; set; }
        [DisplayName("อำเภอ/เขต")]
        public Nullable<int> ampher { get; set; }
        [DisplayName("ตำบล/แขวง")]
        public Nullable<int> district { get; set; }
        [DisplayName("ความคิดเห็น")]
        public string comment { get; set; }
        [DisplayName("รูปภาพเกษตรกร")]
        public string farmer_img { get; set; }
        [DisplayName("รูปถ่ายบัตรประชาชน")]
        public string card_img { get; set; }
        [DisplayName("ธนาคาร")]
        public Nullable<int> bank { get; set; }
        [DisplayName("สถานะ")]
        public Nullable<int> status { get; set; }
        [DisplayName("วันที่ปรับปรุง/แก้ไข")]
        public System.DateTime dateUpdate { get; set; }
        [DisplayName("จังหวัด")]
        public string provinceStr { get; set; }
        [DisplayName("อำเภอ/เขต")]
        public string ampherStr { get; set; }
        [DisplayName("ตำบล/แขวง")]
        public string districtStr { get; set; }

        [DisplayName("แก้ไขโดย")]
        public string adminBy { get; set; }
        public Nullable<int> active { get; set; }

        public virtual active active1 { get; set; }
        public virtual ampher ampher1 { get; set; }
        public virtual bankuser bankuser { get; set; }
        public virtual district district1 { get; set; }
        public virtual family family1 { get; set; }
        public virtual gender gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<landplot> landplots { get; set; }
        public virtual province province1 { get; set; }
        public virtual status status1 { get; set; }
    }
}