//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class software
    {
        [DisplayName("ประเภทซอฟต์แวร์")]
        public int softwareType { get; set; }
        [DisplayName("รหัสซอฟต์แวร์")]
        public string softwareID { get; set; }
        [DisplayName("ชื่อซอฟต์แวร์")]
        public string softwareName { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("ราคาซื้อ")]
        public Nullable<int> price { get; set; }
        [DisplayName("หน่วยที่ซื้อ")]
        public int unitBuy { get; set; }
        [DisplayName("หน่วยที่ใช้")]
        public int unitUse { get; set; }
        [DisplayName("วันที่ซื้อ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<int> dateBuy { get; set; }
        [DisplayName("รูปภาพซอฟต์แวร์")]
        public string softwareImg { get; set; }
        [DisplayName("ลำดับที่")]
        public int IDsoft { get; set; }

        public virtual unit unit { get; set; }
        public virtual unit unit1 { get; set; }
        public virtual softwaretype softwaretype1 { get; set; }
    }
}
