//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmbook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class theory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public theory()
        {
            this.activities = new HashSet<activity>();
        }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ขั้นตอนการทำงาน")]
        public int workProcedure { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ประเภทกสิกรรม")]
        public string farmingType { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ชนิด")]
        public string type { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("สายพันธุ์")]
        public string sepecies { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ผลิตภัณฑ์ที่ได้")]
        public string product { get; set; }
        [DisplayName("โครงการ")]
        public Nullable<int> project { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("ชื่อขั้นตอนการทำงาน")]
        public string workName { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("การเช้าถึง")]
        public int access { get; set; }
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        [DisplayName("แหล่งอ้างอิง")]
        public string reference { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("วันที่ปรับปรุง / แก้ไข")]
        public System.DateTime dateUpdate { get; set; }

        public virtual access access1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity> activities { get; set; }
        public virtual project project1 { get; set; }
        public virtual theorytype theorytype { get; set; }
    }
}
