//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class bankuser
    {
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("ธนาคาร")]
        public Nullable<int> bankID { get; set; }
        [DisplayName("ชื่อบัญชี")]
        public string bankName { get; set; }
        [DisplayName("เลขที่บัญชี")]
        public string bankNo { get; set; }
        [DisplayName("ชื่อเกษตกร")]
        public Nullable<int> regisName { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual register register { get; set; }
    }
}
