//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class standardlist
    {
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("รายการ")]
        public string list { get; set; }
        [DisplayName("กรอกข้อมูล")]
        public Nullable<bool> fillin { get; set; }
        [DisplayName("รูปภาพ")]
        public Nullable<bool> img { get; set; }
        [DisplayName("ชื่อโครงการ")]
        public int IDpro { get; set; }
        [DisplayName("ลำดับรายการที่")]
        public Nullable<int> IDlist { get; set; }

        public virtual project project { get; set; }
    }
}
