//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class staple
    {
        [DisplayName("ประเภทวัตถุดิบ")]
        public int stapleType { get; set; }
        [DisplayName("รหัสวัตถุดิบ")]
        public string stapleID { get; set; }
        [DisplayName("ชื่อวัตถุดิบ")]
        public string stapleName { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("ราคาซื้อ")]
        public Nullable<int> price { get; set; }
        [DisplayName("หน่วยที่ซื้อ")]
        public int unitBuy { get; set; }
        [DisplayName("หน่วยที่ใช้")]
        public int unitUse { get; set; }
        [DisplayName("วันที่ซื้อ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dateBuy { get; set; }
        [DisplayName("รูปภาพวัตถุดิบ")]
        public string stapleImg { get; set; }
        [DisplayName("ลำดับที่")]
        public int IDstap { get; set; }

        public virtual stapletype stapletype1 { get; set; }
        public virtual unit unit { get; set; }
        public virtual unit unit1 { get; set; }
        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase file_stapleImg { get; set; }
    }
}
