//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class @event
    {
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("หัวข้อ")]
        public string subject { get; set; }
        [DisplayName("รายละเอียด")]
        public string description { get; set; }
        [DisplayName("วันที่เริ่มต้น")]
        public System.DateTime start { get; set; }
        [DisplayName("วันที่สิ้นสุด")]
        public Nullable<System.DateTime> end { get; set; }
        [DisplayName("สีข้อความ")]
        public string themeColor { get; set; }
        [DisplayName("เต็มวัน")]
        public Nullable<bool> isFullDay { get; set; }
    }
}
