//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Web;

    public partial class filedetail
    {
        [DisplayName("≈”¥—∫∑’Ë")]
        public int fileID { get; set; }
        [DisplayName("™◊ËÕ‰ø≈Ï")]
        public string fileName { get; set; }
        [DisplayName("¢π“¥‰ø≈Ï")]
        public string fileContentType { get; set; }
        [DisplayName("¢ÈÕ¡Ÿ≈‰ø≈Ï")]
        public byte[] fileData { get; set; }
        /*[Required]*/
        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase files { get; set; }
        public Stream InputStream { get; internal set; }
    }
}
