//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class landplot
    {
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("ชื่อแปลง")]
        public string plotName { get; set; }
        [DisplayName("รหัสแปลง")]
        public string areaCode { get; set; }
        [DisplayName("การถือครองที่ดิน (ประเภทกรรมสิทธิ์)")]
        public int typeOwnership { get; set; }
        [DisplayName("ประเภทเอกสารสิทธิ์")]
        public int license { get; set; }
        [DisplayName("เลขที่เอกสารสิทธิ์ (เลขที่โฉนดที่ดิน)")]
        public string titleDeed { get; set; }
        [DisplayName("ระวาง")]
        public string landSlip { get; set; }
        [DisplayName("เลขที่ดิน")]
        public Nullable<int> landNumber { get; set; }
        [DisplayName("เอกสาร (เอกสารสิทธิ์)")]
        public string license_img { get; set; }
        [DisplayName("เอกสาร (สัญญาเช่า)")]
        public string lease_img { get; set; }
        [DisplayName("ตำบล/แขวง")]
        public Nullable<int> district { get; set; }
        [DisplayName("อำเภอ/เขต")]
        public Nullable<int> ampher { get; set; }
        [DisplayName("จังหวัด")]
        public Nullable<int> province { get; set; }
        [DisplayName("พิกัดเริ่มต้น (ละติจูด)")]
        public string coordinatesStar { get; set; }
        [DisplayName("พิกัดสุดท้าย (ลองจิจูด)")]
        public string coordinatesEnd { get; set; }
        [DisplayName("เนื้อที่")]
        public Nullable<float> areaPlot { get; set; }
        [DisplayName("เนื้อที่หน่วยเป็นไร่")]
        public string areaPlotS { get; set; }
        [DisplayName("รายละเอียดแปลง")]
        public string plotDetails { get; set; }
        [DisplayName("ชื่อเกษตรกร")]
        public Nullable<int> farmerName { get; set; }
        [DisplayName("โครงการ")]
        public Nullable<int> projectName { get; set; }
        [DisplayName("หมายเหตุ")]
        public string note { get; set; }
        [DisplayName("วิธีการรับซื้อ")]
        public Nullable<int> buyMethod { get; set; }
        [DisplayName("สถานะแปลง")]
        public Nullable<int> plotStatus { get; set; }
        [DisplayName("ขั้นตอนการทำงาน")]
        public Nullable<int> theoryName { get; set; }
        [DisplayName("ผู้รับผิดชอบ")]
        public string administrator { get; set; }
        public Nullable<int> active { get; set; }
        [DisplayName("จังหวัด")]
        public string provinceStr { get; set; }
        [DisplayName("อำเภอ/เขต")]
        public string ampherStr { get; set; }
        [DisplayName("ตำบล/แขวง")]
        public string districtStr { get; set; }

        public virtual active active1 { get; set; }
        public virtual ampher ampher1 { get; set; }
        public virtual buymethod buymethod1 { get; set; }
        public virtual district district1 { get; set; }
        public virtual license license1 { get; set; }
        public virtual theory theory { get; set; }
        public virtual project project { get; set; }
        public virtual typeownership typeownership1 { get; set; }
        public virtual province province1 { get; set; }
        public virtual status status { get; set; }
        public virtual register register { get; set; }
        public IEnumerable<SelectListItem> ProvinceList { get; set; }
        public IEnumerable<SelectListItem> AmpherList { get; set; }
        public IEnumerable<SelectListItem> DistrictList { get; set; }
        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase file_license { get; set; }
        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase file_lease { get; set; }
    }
}
