//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class machine
    {
        [DisplayName("ประเภทเครื่องจักร")]
        public int machineType { get; set; }
        [DisplayName("รหัสเครื่องจักร")]
        public string machineID { get; set; }
        [DisplayName("ชื่อเครื่องจักร")]
        public string machineName { get; set; }
        [DisplayName("รายละเอียด")]
        public string detail { get; set; }
        [DisplayName("ราคาซื้อ")]
        public Nullable<int> price { get; set; }
        [DisplayName("หน่วยที่ซื้อ")]
        public int unitBuy { get; set; }
        [DisplayName("หน่วยที่ใช้")]
        public int unitUse { get; set; }
        [DisplayName("วันที่ซื้อ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dateBuy { get; set; }
        [DisplayName("เวลางาน(ชม./ไร่)")]
        public Nullable<int> workTime { get; set; }
        [DisplayName("ค่าพลังงานและเชื้อเพลิง/ชม.")]
        public Nullable<int> fuel { get; set; }
        [DisplayName("ประเภทพลังงาน")]
        public Nullable<int> energy { get; set; }
        [DisplayName("รูปภาพเครื่องจักร")]
        public string machineImg { get; set; }
        [DisplayName("ลำดับที่")]
        public int IDmac { get; set; }

        public virtual energy energy1 { get; set; }
        public virtual machinetype machinetype1 { get; set; }
        public virtual unit unit { get; set; }
        public virtual unit unit1 { get; set; }

        [DataType(DataType.Upload)]
        [DisplayName("Select File")]
        public HttpPostedFileBase file_machineImg { get; set; }
    }
}
