//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class farmdb : DbContext
    {
        public farmdb()
            : base("name=farmdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ampher> amphers { get; set; }
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<bankuser> bankusers { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<family> families { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<landplot> landplots { get; set; }
        public virtual DbSet<license> licenses { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<registertype> registertypes { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<typeownership> typeownerships { get; set; }
        public virtual DbSet<energy> energies { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
