//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class landplot
    {
        [DisplayName("ลำดับที่")]
        public int ID { get; set; }
        [DisplayName("ชื่อแปลง")]
        public string plotName { get; set; }
        [DisplayName("รหัสแปลง")]
        public string areaCode { get; set; }
        [DisplayName("การถือครองที่ดิน (ประเภทกรรมสิทธิ์)")]
        public int typeOwnership { get; set; }
        [DisplayName("ประเภทเอกสารสิทธิ์")]
        public int license { get; set; }
        [DisplayName("เลขที่เอกสารสิทธิ์ (เลขที่โฉนดที่ดิน)")]
        public string titleDeed { get; set; }
        [DisplayName("ระวาง")]
        public string landSlip { get; set; }
        [DisplayName("เลขที่ดิน")]
        public Nullable<int> landNumber { get; set; }
        [DisplayName("เอกสาร (เอกสารสิทธิ์)")]
        public string license_img { get; set; }
        [DisplayName("ตำบล/แขวง")]
        public Nullable<int> district { get; set; }
        [DisplayName("อำเภอ/เขต")]
        public Nullable<int> ampher { get; set; }
        [DisplayName("จังหวัด")]
        public Nullable<int> province { get; set; }
        [DisplayName("พิกัดเริ่มต้น (ละติจูด)")]
        public string coordinatesStar { get; set; }
        [DisplayName("พิกัดสุดท้าย (ลองจิจูด)")]
        public string coordinatesEnd { get; set; }
        [DisplayName("เนื้อที่")]
        public Nullable<float> areaPlot { get; set; }
        [DisplayName("รายละเอียดแปลง")]
        public string plotDetails { get; set; }
        [DisplayName("สถานะแปลง")]
        public Nullable<int> plotStatus { get; set; }
        [DisplayName("โครงการ")]
        public Nullable<int> projectName { get; set; }
        [DisplayName("หมายเหตุ")]
        public string note { get; set; }
        [DisplayName("ชื่อเกษตรกร")]
        public Nullable<int> farmerName { get; set; }
        public string areaPlotS { get; set; }

        public virtual ampher ampher1 { get; set; }
        public virtual district district1 { get; set; }
        public virtual license license1 { get; set; }
        public virtual typeownership typeownership1 { get; set; }
        public virtual province province1 { get; set; }
        public virtual status status { get; set; }
        public virtual project project { get; set; }
        public virtual register register { get; set; }
    }
}
