//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class login
    {
        public int ID { get; set; }
        [DisplayName("Õ’‡¡≈Ï")]
        public string email { get; set; }
        [DisplayName("√À— ºË“π")]
        public string password { get; set; }
    }
}
