//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class profile
    {
        public int ID { get; set; }
        [DisplayName("ชื่อ นามสกุล")]
        public string name { get; set; }
        [DisplayName("หมายเลขบัตรประชาชน")]
        public string cradID { get; set; }
        [DisplayName("เพศ")]
        public int gender { get; set; }
        [DisplayName("วัน/เดือน/ปี เกิด")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> birthday { get; set; }
        [DisplayName("เบอร์โทรศัพท์")]
        public string tel { get; set; }
        [DisplayName("บ้านเลขที่")]
        public Nullable<int> no { get; set; }
        [DisplayName("หมู่ที่")]
        public Nullable<int> moo { get; set; }
        [DisplayName("จังหวัด")]
        public Nullable<int> province { get; set; }
        [DisplayName("อำเภอ/เขต")]
        public Nullable<int> ampher { get; set; }
        [DisplayName("ตำบล/แขวง")]
        public Nullable<int> district { get; set; }
        [DisplayName("อีเมล์")]
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string email { get; set; }
        [DisplayName("รหัสผ่าน")]
        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]
        public string password { get; set; }
        [DisplayName("ประเภทเกษตรกร")]
        public int registerType { get; set; }

        public virtual ampher ampher1 { get; set; }
        public virtual district district1 { get; set; }
        public virtual gender gender1 { get; set; }
        public virtual registertype registertype1 { get; set; }
        public virtual province province1 { get; set; }
    }
}
